version: '3.8'
nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 81
        published: "81"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/nginx-proxy-manager/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /opt/nginx-proxy-manager/etc/letsencrypt
        target: /etc/letsencrypt
        bind:
          create_host_path: true
    networks:
      - nginxpm

networks:
  nginxpm:
    name: network_nginxpm