name: nginxproxymanager
services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    environment:
      - PGID=1000
      - PUID=1000
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - mode: ingress
        target: 5000
        published: "5000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /opt/Dashmachine
        target: /dashmachine/dashmachine/user_data
        bind:
          create_host_path: true