version: '3.8'
services:
  # Yacht
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/yacht/
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true